version: "3"

services:
  backend:
    build:
      context: ./backend
    networks:
      - breitling
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
    networks:
      - breitling
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend

networks:
  breitling:
    driver: bridge
